require_relative 'test_helper'

# The ministry has changed the HTML of the budget pages three times: plain tables up to
# 2013, autogenerated CSS soup in 2014-2018, and semantic-free divs from 2019 onwards.
# Every parser has a branch per format, so each one is exercised here against a real page.
class EntityBreakdownTest < Minitest::Test
  include TestHelper

  def test_reads_a_state_entity_from_the_table_format
    breakdown = EntityBreakdown.new(fixture_document('N_13_E_V_1_101_1_1_2_2_101_1_2.HTM'))

    assert_equal '2013', breakdown.year
    assert_equal '01', breakdown.section
    assert breakdown.is_state_entity?
    assert_equal 'CASA DE SU MAJESTAD EL REY', breakdown.name
  end

  def test_reads_a_state_entity_from_the_autogenerated_css_format
    breakdown = EntityBreakdown.new(fixture_document('N_14_E_V_1_101_1_1_2_2_101_1_2.HTM'))

    assert_equal '2014', breakdown.year
    assert_equal 'CASA DE SU MAJESTAD EL REY', breakdown.name
    assert_equal '7.775,04', breakdown.expenses.first[:amount]
  end

  def test_reads_a_state_entity_from_the_div_format
    breakdown = EntityBreakdown.new(fixture_document('N_21_E_V_1_101_1_1_2_2_101_1_2.HTM'))

    assert_equal '2021', breakdown.year
    assert_equal 'CASA DE SU MAJESTAD EL REY', breakdown.name
    assert_equal '8.431,15', breakdown.expenses.first[:amount]
  end

  def test_fills_in_the_service_and_programme_columns_repeated_down_the_page
    expenses = EntityBreakdown.new(fixture_document('N_13_E_V_1_101_1_1_2_2_101_1_2.HTM')).expenses

    assert_equal({ year: '2013', section: '01', service: '01', programme: '911M',
                   economic_concept: '48',
                   description: 'A familias e instituciones sin fines de lucro',
                   amount: '7.933,71' },
                 expenses.first)
  end

  # The amount of a heading is only shown when the subtotal closes, several rows below the
  # description, so the parser has to pair them up. The last one closes the whole entity.
  def test_pairs_each_heading_with_the_subtotal_that_closes_it
    expenses = EntityBreakdown.new(fixture_document('N_13_E_V_1_101_1_1_2_2_101_1_2.HTM')).expenses

    assert_equal({ year: '2013', section: '01', service: '',
                   description: 'CASA DE SU MAJESTAD EL REY', amount: '7.933,71' },
                 expenses.last)
  end

  def test_reads_a_non_state_entity
    breakdown = EntityBreakdown.new(fixture_document('N_13_E_V_1_104_2_1_425_1_1301_2_2_1.HTM'))

    refute breakdown.is_state_entity?
    assert_equal '25', breakdown.section
    assert_equal '301', breakdown.entity
    assert_equal 'CENTRO NACIONAL DE INTELIGENCIA', breakdown.name
    assert_equal [{ id: '301', name: 'CENTRO NACIONAL DE INTELIGENCIA' }], breakdown.children
  end
end

class IncomeBreakdownTest < Minitest::Test
  include TestHelper

  def test_reads_income_from_the_table_format
    breakdown = IncomeBreakdown.new(fixture_document('N_13_E_R_2_102_1_2_115_1_1104_1.HTM'))

    assert_equal '2013', breakdown.year
    assert_equal '2', breakdown.entity_type
    assert_equal '15', breakdown.section
    assert_equal '104', breakdown.entity_id
    assert_equal 'COMISIONADO PARA EL MERCADO DE TABACOS', breakdown.entity_name
    assert_equal 7, breakdown.income.size
  end

  # Accented characters only come out right if the page is handed over as raw bytes, so
  # that Nokogiri uses the windows-1252 charset the page declares.
  def test_keeps_the_accents_of_the_original_page
    breakdown = IncomeBreakdown.new(fixture_document('N_13_E_R_2_102_1_2_115_1_1104_1.HTM'))

    assert_equal 'MINISTERIO DE HACIENDA Y ADMINISTRACIONES PÚBLICAS', breakdown.section_name
  end

  def test_reads_income_from_the_div_format
    breakdown = IncomeBreakdown.new(fixture_document('N_21_E_R_2_102_1_2_119_1_1103_1.HTM'))

    assert_equal '19', breakdown.section
    assert_equal 'MINISTERIO DE TRABAJO Y ECONOMÍA SOCIAL', breakdown.section_name
    assert_equal 'ORGANISMO ESTATAL INSPECCIÓN DE TRABAJO Y SEGURIDAD SOCIAL', breakdown.entity_name
    assert_equal({ year: '2021', section: '19', service: '103', programme: nil,
                   economic_concept: '40', description: 'De la Administración del Estado',
                   amount: '168.127,07' },
                 breakdown.income.first)
  end

  def test_lists_the_institutions_it_describes
    breakdown = IncomeBreakdown.new(fixture_document('N_13_E_R_2_102_1_2_115_1_1104_1.HTM'))

    assert_equal [
      { section: '15', service: nil, description: 'MINISTERIO DE HACIENDA Y ADMINISTRACIONES PÚBLICAS' },
      { section: '15', service: '104', description: 'COMISIONADO PARA EL MERCADO DE TABACOS' },
    ], breakdown.institutions
  end
end

class ProgrammeBreakdownTest < Minitest::Test
  include TestHelper

  def test_reads_a_social_security_programme_from_the_table_format
    breakdown = ProgrammeBreakdown.new(fixture_document('N_13_E_R_31_2_1_G_1_1_1224M_P.HTM'))

    assert_equal '2013', breakdown.year
    assert_equal ['60', 'SEGURIDAD SOCIAL'], breakdown.get_section_id_and_name
    assert_equal ['224M', 'Prestaciones económicas por cese de actividad'],
                 breakdown.get_programme_id_and_name
  end

  def test_reads_a_social_security_programme_from_the_autogenerated_css_format
    breakdown = ProgrammeBreakdown.new(fixture_document('N_14_E_R_31_2_1_G_1_1_1224M_P.HTM'))

    assert_equal ['60', 'SEGURIDAD SOCIAL'], breakdown.get_section_id_and_name
    assert_equal({ year: '2014', section: '60', service: '01', programme: '224M',
                   economic_concept: '48',
                   description: 'A familias e instituciones sin fines de lucro',
                   amount: '11.060,00' },
                 breakdown.expenses.first)
  end

  def test_reads_a_social_security_programme_from_the_div_format
    breakdown = ProgrammeBreakdown.new(fixture_document('N_21_E_R_31_2_1_G_1_1_1290A_P.HTM'))

    assert_equal ['290A', 'Gestión y administración de la Inclusión de la Seguridad Social ' \
                          'y de la Migración. Mecanismo de Recuperación y Resiliencia'],
                 breakdown.get_programme_id_and_name
  end

  # These subtotals are not in the expense list, but we need them to rebuild the hierarchy
  def test_lists_the_institutions_behind_the_programme
    breakdown = ProgrammeBreakdown.new(fixture_document('N_13_E_R_31_2_1_G_1_1_1224M_P.HTM'))

    assert_equal [
      { section: '60', service: nil, description: 'SEGURIDAD SOCIAL' },
      { section: '60', service: '01',
        description: 'PENSIONES Y PRESTACIONES ECONÓMICAS DE LA SEGURIDAD SOCIAL' },
    ], breakdown.institutions
  end
end

class GenericBreakdownTest < Minitest::Test
  include TestHelper

  def test_looks_up_an_official_total_by_its_description
    breakdown = GenericBreakdown.new(fixture_document('N_13_E_R_6_2_801_1_3.HTM'))

    assert_equal '135.147.139,64', breakdown.get_value_by_description('TOTAL OPERACIONES NO FINANCIERAS')
  end

  def test_points_back_at_the_page_on_the_ministry_site
    breakdown = GenericBreakdown.new(fixture_document('N_13_E_R_6_2_801_1_3.HTM'))

    assert_equal '2013', "20#{breakdown.year}"
    assert breakdown.is_final
    assert_equal 'http://www.sepg.pap.minhap.gob.es/Presup/PGE2013Ley/MaestroDocumentos/' \
                 'PGE-ROM/doc/HTM/N_13_E_R_6_2_801_1_3.HTM',
                 breakdown.get_url
  end
end

class BudgetTest < Minitest::Test
  include TestHelper

  # Amounts are published in thousands of euros, in spanish notation
  def test_converts_amounts_to_whole_euros
    assert_equal 135147139640, Budget.convert_number('135.147.139,64')
    assert_equal 7933710, Budget.convert_number('7.933,71')
    assert_equal '', Budget.convert_number(nil)
    assert_equal '', Budget.convert_number('')
  end

  def test_picks_the_breakdowns_apart_by_kind
    with_fixture_source do |source|
      budget = Budget.new(source, true)

      assert_equal 4, budget.entity_breakdowns.size
      assert_equal 3, budget.programme_breakdowns.size
      assert_equal 3, budget.income_breakdowns.size
    end
  end

  def test_finds_a_summary_page_by_year_and_id
    with_fixture_source do |source|
      breakdown = Budget.new(source, true).generic_breakdown('2013', 'R_6_2_801_1_3')

      assert_equal '135.147.139,64', breakdown.get_value_by_description('TOTAL OPERACIONES NO FINANCIERAS')
    end
  end

  def test_complains_when_a_summary_page_is_not_in_the_budget
    with_fixture_source do |source|
      error = assert_raises(RuntimeError) do
        Budget.new(source, true).generic_breakdown('2013', 'R_6_2_899_9_9')
      end
      assert_match 'N_13_E_R_6_2_899_9_9.HTM', error.message
    end
  end
end
