$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

require 'minitest/autorun'
require 'tmpdir'
require 'zip'

require 'budget'
require 'budget_parser'
require 'budget_summary_renderer'

module TestHelper
  ROOT = File.expand_path('..', __dir__)

  # A handful of real budget pages, the smallest of their kind, covering the three formats
  # the ministry has used over the years: tables (up to 2013), autogenerated CSS soup
  # (2014-2018) and semantic-free divs (2019 onwards).
  #
  # They are kept as plain files, laid out the way an archive lays them out, so that they
  # can be read and grepped like any other file. The parser normally reads a .zip, so the
  # tests that need one build it from these.
  FIXTURE_BUDGET = File.expand_path('fixtures/budget', __dir__)

  def with_fixture_source
    BudgetSource.open(FIXTURE_BUDGET) { |source| yield source }
  end

  def fixture_document(name)
    with_fixture_source do |source|
      document = source.document(name)
      refute_nil document, "there is no #{name} under test/fixtures/budget"
      document
    end
  end

  # The fixture pages, packed into a throwaway archive
  def with_fixture_archive
    with_archive(Dir.glob(File.join(FIXTURE_BUDGET, '**', '*.HTM')).sort.to_h { |page|
      [page.delete_prefix("#{FIXTURE_BUDGET}/"), File.binread(page)]
    }) { |archive| yield archive }
  end

  def with_archive(entries)
    Dir.mktmpdir do |dir|
      archive = File.join(dir, 'budget.zip')
      Zip::File.open(archive, create: true) do |zip|
        entries.each { |name, contents| zip.get_output_stream(name) { |io| io.write contents } }
      end
      yield archive
    end
  end
end
