$LOAD_PATH.unshift File.expand_path('../lib', __dir__)

require 'minitest/autorun'
require 'tmpdir'

require 'budget'
require 'budget_parser'
require 'budget_summary_renderer'

module TestHelper
  ROOT = File.expand_path('..', __dir__)

  # A handful of real budget pages, small ones, covering the three formats the ministry
  # has used over the years: tables (up to 2013), autogenerated CSS soup (2014-2018) and
  # semantic-free divs (2019 onwards).
  FIXTURE_ZIP = File.expand_path('fixtures/budget_pages.zip', __dir__)

  def with_fixture_source
    BudgetSource.open(FIXTURE_ZIP) { |source| yield source }
  end

  def fixture_document(name)
    with_fixture_source do |source|
      document = source.document(name)
      refute_nil document, "fixture #{name} is missing from budget_pages.zip"
      # Detach it from the archive, which is closed on the way out
      Struct.new(:name, :read).new(document.name, document.read)
    end
  end
end
